zigdon/xkcd-Bucket

- bucket.pl
Any bot op could get or set the server password with e.g. "Bucket: get server_pass", which is not a good thing.
I didn't intend to introduce this possibility, but I guess I just never noticed it was there in the output of "Bucket: set" until now. Sorry, @zigdon!
> Don't allow setting server_pass from IRC

- bucket.pl
Replaced with the value of `$chl` when the factoid is output.
Consider this a baby step on the way to learning enough Perl to address #54…
Please let me know if there are any code style issues I need to address.
> Add $channel placeholder

- bucket.pl
Of course, POE::Component::IRC uses 0 to mean on and 1 to mean off, so
needs a little logical reversal to work (provided).
This is useful for people who might use Bucket behind a bouncer and want to
let the bouncer take care of flood protection.
> Add flood_control option: 1 = on, 0 = off

- bucket.pl
Cache refill needs to use $var, not $full, so the effects of any substitutions
are used when querying the DB. This prevents trying to query for values of e.g.
"$verbing" instead of "$verb".
Been testing for a few days and haven't noticed any more empty substitutions like we discussed on IRC, @zigdon. I think it's fixed.
> Refill large var cache even for special cases

- bucket.pl
Fixes managing vars for bots with lots of them. Presumably Bucket has fewer variables than my bot does, and has never run into this problem.
> Use &say_long for 'list vars' to avoid truncation

- bucket.pl
Closes #64 (how appropriate that the test case was "Nowhere Man")
Thanks again to @belak for poking around in dark places I forgot all about and suggesting the fix.
> Fix "do you know" matching in places it shouldn't

- bucket.pl
Intended to fix #43. Hat tip to @barometz for the comment on d82b71d
> say_long for "list ignored"; use make_list too

- bucket.pl
Fixes issue #74. `tail -f` works flawlessly now.
> Make logfile hot so log writes are flushed to disk immediately

- bucket.pl
Resolves #76 in most cases—except if the factoid that can't be triggered begins with a `nick:` highlight where the `nick` exists on the channel.
It would be possible to have the factoid search look for the incoming line both with and without the prefix, preferring the result set with the prefix if it is non-empty…but that's much more work for minimal benefit. (Future visitors to this repository can feel free to revive the discussion on #76, or open a new issue, if the lack of this functionality causes problems.)
> Verify that $to exists before stripping it from the line

- bucket.pl
- plugins/README
Intended to make it possible for plugins to intercept e.g. "don't know" being fired, but hopefully has broader applications than the original idea of adding a signal in `elsif ( $bag{addressed} )`.
I will use this PR to quickly pull the new signal into my production instance and start toying with writing a plugin that uses it. Will merge if it serves the purpose correctly, and make changes if not.
> Add plugin signal for when no factoids/functions match

- bucket.pl
- plugins/README
New signal called before expanding variables in a factoid. The tidbit itself is passed in as a reference.
Added for use by my plugin that implements the new syntax described in #89.
> Add pre_expand signal for filtering tidbits

- bucket.pl
Change the confirmation for item deletion from "destroying $item" to "deleting item $item", which is more consistent with the command used to do so ("delete item #20"). The last few times I've wanted to delete an item it took me three tries to get there ("destroy item #20", "destroy #20") and I feel this might help.
(augh, sorry about the branch name. Editing through the Github interface, should've caught that earlier)
> Item deletion message: destroy -> delete

- bucket.pl
Got this pushed up a few minutes ago, so here's the long-awaited PR to fix Bucket's var cache self-corruption problem.
> Fix behavior after adding new large var values

- plugins/plugin.quotes.pl
Bucket core already does this before signaling. Having the quotes plugin do it again just results in broken quotes if the line begins with a single word and a colon. Resolves #28.
> Remove unnecessary prefix stripping in quotes plugin

- bucket.pl
- bucket.sql
Migrated my bucket clone to a newer system, ran in to some headaches due to newer MySQL and Perl versions. 
MySQL STRICT_TRANS_TABLES was causing issues when setting factiods.  RE field was not being set by bucket.pl and therefore MySQL just dropped the transaction.  If RE is set to have a default value, this is not a problem.
Perl was complaining about unescaped left braces on a number of regex lines.  I guess this was deprecated at some point.
> Minor fixups for newer versions of MySQL and Perl

- bucket.pl
Created new "lookup" internal command specifically for handling lookups. Lookups no longer hijack the "fact" command routine, and they now look more like a "what was that" without the var expansion info.
Resolves #95.
> Change lookup format to be more like a lookup

- bucket.pl
For instances of Bucket other than the main one, users may have no idea who Zigdon is or how to contact him, because they are on a different IRC network. Linking to Bucket's GitHub issue tracker will make getting a report of these errors more likely.
Happened to notice these error messages while reading through the code to work on another issue.
> Refer errors to GitHub issues as well as Zigdon

- bucket.pl
See #69. Bucket doesn't actually seem to learn from someone saying, "Bucket, I am a tester." for example. Even if it was picked up, code later in that function would reject learning such a factoid ("Please don't edit your own factoids, $bag{who}."). So this check is pointless.
> Remove unreachable "I am" code in &db_success

- bucket.pl
Fixes #73.
For now, we'll continue to assume that channel names always start with `#`.
> join/part: Let channel names be any non-whitespace

- bucket.pl
On PART, prune the user's cached gender only if Bucket no longer shares any channels with them.
KICK did not prune the gender cache at all before, but it now follows the same (new) logic as PART.
> Selectively prune gender cache on PART and KICK

- bucket.pl
Had trouble with this line when trying to set up a fresh Bucket instance tonight.
Patch in 304dc4948a5fa20c82f413ffcbac28fc67a59bab (from #129) was slightly under tested, I guess. Whoops.
Sorry y'all. But nobody opened an issue for it in two years, so maybe there are even fewer Bucket users left than I thought. 😅
> Fix undefined local `$who` in gender cache pruning

- bucket.pl
Someone parting or getting kicked now causes Bucket to crash with an error about treating an undefined value as an ARRAY reference.
I can only assume some subtle behavior changes have happened in the years and Perl versions since I last ran this code, and something that used to be allowed is no longer kosher. There were no issues initially with #129 (where these `if` blocks came from) or I'm positive I wouldn't have merged the patch.
> Try to fix parts/quits now causing Bucket to crash

- bucket.pl
- bucket.sql
I'm running Bucket on a PlanetScale database now, which aims to be MySQL 8 compatible. (It lets me avoid having to manage MySQL hosting myself on my silly little VPS.)
Upstream MySQL 8 has deprecated the behavior where inserting/updating a TIMESTAMP column with NULL uses the DEFAULT. PlanetScale emulates this, of course, and trying to e.g. `Bucket, I am male` yields an error:
`Column 'stamp' cannot be null (errno 1048) (sqlstate 23000)`
To apply the SQL schema change from this patch to an existing database, run this query:
```sql
ALTER TABLE `genders` MODIFY COLUMN `stamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp();
```
> Fix updating genders on MySQL 8-like clients

- bucket.pl
Quick test shows that this doesn't cause a crash under the same conditions, but I'm also not positive that the problem was consistently triggered so this is 50% a stab in the dark.
I'll run this patch in my Bucket bot for a while and see if it continues randomly quitting when people quit/get kicked.
> Different approach to the can't-use-string-as-array-ref bug
